users = [
    {name = "Admin", password = "Schattenherz", role = "GameMaster"},
    {name = "Nyssara", password = "Schattenfluch", role = "Player"},
    {name = "Gnodomir", password = "Goot", role = "Player"},
    {name = "Marcus", password = "Trizepts", role = "Player"},
    {name = "Hector", password = "Paladin", role = "Player"},
    {name = "Vishuda", password = "Taia", role = "Player"}]