users = [
    {name = "Admin", password = "Schattenherz", role = "GameMaster"},
    {name = "Nyssara", password = "Schattenfluch", role = "Player"},
    {name = "Gnodomir", password = "Goot", role = "Player"},
    {name = "Marcus", password = "Trizepts", role = "Player"},
    {name = "Hector", password = "Paladin", role = "Player"},
    {name = "Vishuda", password = "Taia", role = "Player"},
    {name = "user", password = "user", role = "Player"},
    {name = "Jan", password = "", role = "Player"},
    {name = "Niklas", password = "test", role = "Player"},
    {name = "Daniel", password = "test2", role = "Player"},
    {name = "Hartmut", password = "test3", role = "Player"},
    {name = "Timo", password = "test4", role = "Player"},]